- id: osv-scanner
  name: osv-scanner
  description: "osv-scanner: ..."
  entry: osv-scanner --recursive .
  language: system
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  pass_filenames: false
- id: govulncheck
  name: govulncheck
  description: "govulncheck: ..."
  entry: govulncheck
  language: system
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  pass_filenames: false