- id: osv-scanner
  name: osv-scanner
  description: "osv-scanner: ..."
  entry: osv-scanner --recursive .
  language: system
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  # types_or: [python, pyi]
  types: [text]